/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakar.view;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import sistempakar.controller.ControllerLearning;

/**
 *
 * @author adesuryansyah
 */
public class popUPLearning extends javax.swing.JInternalFrame {

    ControllerLearning cbt;
    
    
       
    
    /**
     * Creates new form popUPLearning
     */
    public popUPLearning() {
        initComponents();
        setLocation(300, 60);
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbPertumbuhan1 = new javax.swing.JRadioButton();
        rbPertumbuhan0 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbGerakan1 = new javax.swing.JRadioButton();
        rbGerakan0 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbNafsuMkn1 = new javax.swing.JRadioButton();
        rbNafsuMkn0 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbGesekanBdn1 = new javax.swing.JRadioButton();
        rbGesekanBdn0 = new javax.swing.JRadioButton();
        rbFlashing0 = new javax.swing.JRadioButton();
        rbBorok0 = new javax.swing.JRadioButton();
        rbBorok1 = new javax.swing.JRadioButton();
        rbFlashing1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbPendarahanMata1 = new javax.swing.JRadioButton();
        rbPendarahanMata0 = new javax.swing.JRadioButton();
        rbPendarahanMulut0 = new javax.swing.JRadioButton();
        rbPendarahanMulut1 = new javax.swing.JRadioButton();
        rbPendarahanTutupInsang0 = new javax.swing.JRadioButton();
        rbPendarahanTutupInsang1 = new javax.swing.JRadioButton();
        rbPendarahanHidung1 = new javax.swing.JRadioButton();
        rbPendarahanHidung0 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbInsang1 = new javax.swing.JRadioButton();
        rbInsang0 = new javax.swing.JRadioButton();
        rbSisik0 = new javax.swing.JRadioButton();
        rbSisik1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbMata = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        rbLendir1 = new javax.swing.JRadioButton();
        rbLendir0 = new javax.swing.JRadioButton();
        rbSirip1 = new javax.swing.JRadioButton();
        rbSirip0 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rbPatogen1 = new javax.swing.JRadioButton();
        rbPatogen0 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        cbTubuh = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cbMati = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rbLintah0 = new javax.swing.JRadioButton();
        rbLintah1 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        cbEkor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setClosable(true);
        setTitle("Tambah Data Learning");
        setPreferredSize(new java.awt.Dimension(710, 460));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("1. PERTUMBUHAN");

        rbPertumbuhan1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPertumbuhan1.setText("NORMAL");
        rbPertumbuhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPertumbuhan1ActionPerformed(evt);
            }
        });

        rbPertumbuhan0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPertumbuhan0.setText("LAMBAT");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("2. GERAKAN");

        rbGerakan1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGerakan1.setText("AKTIF");
        rbGerakan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGerakan1ActionPerformed(evt);
            }
        });

        rbGerakan0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGerakan0.setText("LAMBAT / LEMAH");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("3. NAFSU MAKAN");

        rbNafsuMkn1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbNafsuMkn1.setText("IYA");
        rbNafsuMkn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNafsuMkn1ActionPerformed(evt);
            }
        });

        rbNafsuMkn0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbNafsuMkn0.setText("TIDAK");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel7.setText("6. BOROK");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel8.setText("5. FLASHING / BERENANG ");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel9.setText("4. GESEKAN BADAN");

        rbGesekanBdn1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGesekanBdn1.setText("IYA");
        rbGesekanBdn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGesekanBdn1ActionPerformed(evt);
            }
        });

        rbGesekanBdn0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGesekanBdn0.setText("TIDAK");

        rbFlashing0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbFlashing0.setText("LAMBAT / LEMAH");

        rbBorok0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbBorok0.setText("TIDAK");

        rbBorok1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbBorok1.setText("IYA");
        rbBorok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBorok1ActionPerformed(evt);
            }
        });

        rbFlashing1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbFlashing1.setText("AKTIF");
        rbFlashing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFlashing1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel10.setText("     TIDAK BERATURAN");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setText("7. PENDARAHAN PADA :");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel12.setText("     - MATA");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel13.setText("     - MULUT");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel14.setText("     - HIDUNG");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel15.setText("     - TUTUP INSANG");

        rbPendarahanMata1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMata1.setText("IYA");
        rbPendarahanMata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendarahanMata1ActionPerformed(evt);
            }
        });

        rbPendarahanMata0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMata0.setText("TIDAK");

        rbPendarahanMulut0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMulut0.setText("TIDAK");

        rbPendarahanMulut1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMulut1.setText("IYA");
        rbPendarahanMulut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendarahanMulut1ActionPerformed(evt);
            }
        });

        rbPendarahanTutupInsang0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanTutupInsang0.setText("TIDAK");

        rbPendarahanTutupInsang1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanTutupInsang1.setText("IYA");
        rbPendarahanTutupInsang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendarahanTutupInsang1ActionPerformed(evt);
            }
        });

        rbPendarahanHidung1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanHidung1.setText("IYA");
        rbPendarahanHidung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendarahanHidung1ActionPerformed(evt);
            }
        });

        rbPendarahanHidung0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanHidung0.setText("TIDAK");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("8. INSANG");

        rbInsang1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbInsang1.setText("MERAH HATI");
        rbInsang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInsang1ActionPerformed(evt);
            }
        });

        rbInsang0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbInsang0.setText("PUCAT");

        rbSisik0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSisik0.setText("RONTOK");

        rbSisik1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSisik1.setText("MULUS");
        rbSisik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSisik1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel16.setText("9. SISIK");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel17.setText("10 . MATA");

        cbMata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jernih", "Menonjol", "Bura Putih" }));
        cbMata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMataActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel19.setText("11. LENDIR");

        rbLendir1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLendir1.setText("NORMAL");
        rbLendir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLendir1ActionPerformed(evt);
            }
        });

        rbLendir0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLendir0.setText("BERLEBIHAN");

        rbSirip1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSirip1.setText("MULUS");
        rbSirip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSirip1ActionPerformed(evt);
            }
        });

        rbSirip0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSirip0.setText("RUSAK");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel20.setText("12. SIRIP");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel21.setText("13. PATOGEN");

        rbPatogen1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPatogen1.setText("NORMAL");
        rbPatogen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPatogen1ActionPerformed(evt);
            }
        });

        rbPatogen0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPatogen0.setText("RENDAH");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel22.setText("14. MATI");

        cbTubuh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hitam", "Besih", "Putih Bercorak" }));
        cbTubuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTubuhActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel24.setText("15. TUBUH");

        cbMati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Tidak Ada", "0 >= 6", "0 <= 5" }));
        cbMati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatiActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel25.setText("16. APAKAH TERDAPAT  LINTAH ATAU WARNA KEHITAMAN");

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel26.setText("        PADA SIRIP DAN TUTUP INSANG");

        rbLintah0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLintah0.setText("TIDAK");

        rbLintah1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLintah1.setText("IYA");
        rbLintah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLintah1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel28.setText("17. EKOR");

        cbEkor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mulus", "Rusak", "Kemerahan", "Rusak dan Kemrahan" }));
        cbEkor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEkorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75)
                                .addComponent(rbPertumbuhan1))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbBorok1)
                                    .addComponent(rbGerakan1)
                                    .addComponent(rbNafsuMkn1)
                                    .addComponent(rbGesekanBdn1)
                                    .addComponent(rbFlashing1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFlashing0)
                            .addComponent(rbBorok0)
                            .addComponent(rbGesekanBdn0)
                            .addComponent(rbNafsuMkn0)
                            .addComponent(rbGerakan0)
                            .addComponent(rbPertumbuhan0)
                            .addComponent(rbPendarahanMulut0)
                            .addComponent(rbPendarahanMata0)
                            .addComponent(rbPendarahanHidung0)
                            .addComponent(rbPendarahanTutupInsang0)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPendarahanHidung1)
                            .addComponent(rbPendarahanMulut1)
                            .addComponent(rbPendarahanTutupInsang1)
                            .addComponent(rbPendarahanMata1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbInsang1)
                                    .addComponent(rbSisik1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbSisik0)
                                    .addComponent(rbInsang0))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(29, 29, 29)
                        .addComponent(rbLendir1)
                        .addGap(18, 18, 18)
                        .addComponent(rbLendir0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(rbSirip1)
                        .addGap(24, 24, 24)
                        .addComponent(rbSirip0))
                    .addComponent(jLabel20)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(rbLintah1)
                            .addGap(44, 44, 44)
                            .addComponent(rbLintah0))
                        .addComponent(jLabel26))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(34, 34, 34)
                            .addComponent(cbMata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbPatogen1)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbPatogen0))
                                .addComponent(cbTubuh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMati, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(39, 39, 39)
                        .addComponent(cbEkor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbMata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbLendir1)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbLendir0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(rbSirip1)
                            .addComponent(rbSirip0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(rbPatogen1)
                            .addComponent(rbPatogen0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(cbMati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTubuh)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbLintah1)
                            .addComponent(rbLintah0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEkor)
                            .addComponent(jLabel28))
                        .addGap(298, 298, 298))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbPertumbuhan1)
                            .addComponent(rbPertumbuhan0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbGerakan1)
                            .addComponent(rbGerakan0)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNafsuMkn1)
                            .addComponent(rbNafsuMkn0)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbGesekanBdn1)
                            .addComponent(rbGesekanBdn0)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(rbBorok1)
                                    .addComponent(rbBorok0)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbFlashing1)
                                .addComponent(rbFlashing0)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rbPendarahanMata1)
                            .addComponent(rbPendarahanMata0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(rbPendarahanMulut1)
                            .addComponent(rbPendarahanMulut0))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rbPendarahanHidung1)
                            .addComponent(rbPendarahanHidung0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rbPendarahanTutupInsang0)
                            .addComponent(rbPendarahanTutupInsang1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbInsang1)
                            .addComponent(rbInsang0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(rbSisik1)
                            .addComponent(rbSisik0))
                        .addGap(236, 236, 236))))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TAMBAH");

        btnOK.setBackground(new java.awt.Color(0, 204, 204));
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbGerakan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGerakan1ActionPerformed
        String radioTextGerakan ="";
        
        if(rbGerakan0.isSelected()){
            radioTextGerakan = rbGerakan0.getText();
            radioTextGerakan = "";
        }else{
            radioTextGerakan = rbPertumbuhan1.getText();
            radioTextGerakan = "1";
        }
    }//GEN-LAST:event_rbGerakan1ActionPerformed

    private void cbMataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMataActionPerformed
        String txtCbMata = "";
        String itemText = (String)cbMata.getSelectedItem();
        txtCbMata = (itemText);
    }//GEN-LAST:event_cbMataActionPerformed

    private void rbPertumbuhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPertumbuhan1ActionPerformed
        String radioTextPertumbuhan = "";
        
        if (rbPertumbuhan0.isSelected()){
            radioTextPertumbuhan = rbPertumbuhan0.getText();
            radioTextPertumbuhan = "0";
        }else{
            radioTextPertumbuhan = rbPertumbuhan1.getText();
            radioTextPertumbuhan = "1";
        }
    }//GEN-LAST:event_rbPertumbuhan1ActionPerformed

    private void rbNafsuMkn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNafsuMkn1ActionPerformed
        String radioTextNafsuMakan = "";

        if (rbNafsuMkn0.isSelected()){
            radioTextNafsuMakan = rbNafsuMkn0.getText();
            radioTextNafsuMakan = "0";
        }else{
            radioTextNafsuMakan = rbNafsuMkn1.getText();
            radioTextNafsuMakan = "1";
        }
    }//GEN-LAST:event_rbNafsuMkn1ActionPerformed

    private void rbGesekanBdn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGesekanBdn1ActionPerformed
        String radioTextGesekanBadan = "";

        if (rbGesekanBdn0.isSelected()){
            radioTextGesekanBadan = rbGesekanBdn0.getText();
            radioTextGesekanBadan = "0";
        }else{
            radioTextGesekanBadan = rbGesekanBdn1.getText();
            radioTextGesekanBadan = "1";
        }
    }//GEN-LAST:event_rbGesekanBdn1ActionPerformed

    private void cbMatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatiActionPerformed
        String txtCbMati = "";
        String itemText = (String)cbMati.getSelectedItem();
        txtCbMati = itemText;
    }//GEN-LAST:event_cbMatiActionPerformed

    private void cbTubuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTubuhActionPerformed
        String txtCbTubuh = "";
        String itemText = (String)cbTubuh.getSelectedItem();
        txtCbTubuh = itemText;
    }//GEN-LAST:event_cbTubuhActionPerformed

    private void cbEkorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEkorActionPerformed
        String txtCbEkor = "";
        String itemText = (String)cbEkor.getSelectedItem();
        txtCbEkor = itemText;
    }//GEN-LAST:event_cbEkorActionPerformed

    private void rbFlashing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFlashing1ActionPerformed
        String radioTextFlashing = "";

        if (rbFlashing0.isSelected()){
            radioTextFlashing = rbFlashing0.getText();
            radioTextFlashing = "0";
        }else{
            radioTextFlashing = rbFlashing1.getText();
            radioTextFlashing = "1";
        }
    }//GEN-LAST:event_rbFlashing1ActionPerformed

    private void rbBorok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBorok1ActionPerformed
        String radioTextBorok = "";

        if (rbBorok0.isSelected()){
            radioTextBorok = rbBorok0.getText();
            radioTextBorok = "0";
        }else{
            radioTextBorok = rbBorok1.getText();
            radioTextBorok = "1";
        }
    }//GEN-LAST:event_rbBorok1ActionPerformed

    private void rbPendarahanMata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendarahanMata1ActionPerformed
        String radioTextPMata = "";

        if (rbPendarahanMata0.isSelected()){
            radioTextPMata = rbPendarahanMata0.getText();
            radioTextPMata = "0";
        }else{
            radioTextPMata = rbPendarahanMata1.getText();
            radioTextPMata = "1";
        }
    }//GEN-LAST:event_rbPendarahanMata1ActionPerformed

    private void rbPendarahanMulut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendarahanMulut1ActionPerformed
        String radioTextPMulut = "";

        if (rbPendarahanMulut0.isSelected()){
            radioTextPMulut = rbPendarahanMulut0.getText();
            radioTextPMulut = "0";
        }else{
            radioTextPMulut = rbPendarahanMulut1.getText();
            radioTextPMulut = "1";
        }
    }//GEN-LAST:event_rbPendarahanMulut1ActionPerformed

    private void rbPendarahanHidung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendarahanHidung1ActionPerformed
        String radioTextPHidung = "";

        if (rbPendarahanHidung0.isSelected()){
            radioTextPHidung = rbPendarahanHidung0.getText();
            radioTextPHidung = "0";
        }else{
            radioTextPHidung = rbPendarahanHidung1.getText();
            radioTextPHidung = "1";
        }
    }//GEN-LAST:event_rbPendarahanHidung1ActionPerformed

    private void rbPendarahanTutupInsang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendarahanTutupInsang1ActionPerformed
        String radioTextPTtpInsang = "";

        if (rbPendarahanTutupInsang0.isSelected()){
            radioTextPTtpInsang = rbPendarahanTutupInsang0.getText();
            radioTextPTtpInsang = "0";
        }else{
            radioTextPTtpInsang = rbPendarahanTutupInsang1.getText();
            radioTextPTtpInsang = "1";
        }
    }//GEN-LAST:event_rbPendarahanTutupInsang1ActionPerformed

    private void rbInsang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInsang1ActionPerformed
        String radioTextInsang = "";

        if (rbInsang0.isSelected()){
            radioTextInsang = rbInsang0.getText();
            radioTextInsang = "0";
        }else{
            radioTextInsang = rbInsang1.getText();
            radioTextInsang = "1";
        }
    }//GEN-LAST:event_rbInsang1ActionPerformed

    private void rbSisik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSisik1ActionPerformed
        String radioTextSisik = "";

        if (rbSisik0.isSelected()){
            radioTextSisik = rbSisik0.getText();
            radioTextSisik = "0";
        }else{
            radioTextSisik = rbSisik1.getText();
            radioTextSisik = "1";
        }
    }//GEN-LAST:event_rbSisik1ActionPerformed

    private void rbLendir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLendir1ActionPerformed
        String radioTextLendir = "";

        if (rbLendir0.isSelected()){
            radioTextLendir = rbLendir0.getText();
            radioTextLendir = "0";
        }else{
            radioTextLendir = rbLendir1.getText();
            radioTextLendir = "1";
        }
    }//GEN-LAST:event_rbLendir1ActionPerformed

    private void rbSirip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSirip1ActionPerformed
        String radioTextSirip = "";

        if (rbSirip0.isSelected()){
            radioTextSirip = rbSirip0.getText();
            radioTextSirip = "0";
        }else{
            radioTextSirip = rbSirip1.getText();
            radioTextSirip = "1";
        }
    }//GEN-LAST:event_rbSirip1ActionPerformed

    private void rbPatogen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPatogen1ActionPerformed
        String radioTextPatogen = "";

        if (rbPatogen0.isSelected()){
            radioTextPatogen = rbPatogen0.getText();
            radioTextPatogen = "0";
        }else{
            radioTextPatogen = rbPatogen1.getText();
            radioTextPatogen = "1";
        }
    }//GEN-LAST:event_rbPatogen1ActionPerformed

    private void rbLintah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLintah1ActionPerformed
        String radioTextLintah = "";

        if (rbLintah0.isSelected()){
            radioTextLintah = rbLintah0.getText();
            radioTextLintah = "0";
        }else{
            radioTextLintah = rbLintah1.getText();
            radioTextLintah = "1";
        }
    }//GEN-LAST:event_rbLintah1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbEkor;
    private javax.swing.JComboBox<String> cbMata;
    private javax.swing.JComboBox<String> cbMati;
    private javax.swing.JComboBox<String> cbTubuh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbBorok0;
    private javax.swing.JRadioButton rbBorok1;
    private javax.swing.JRadioButton rbFlashing0;
    private javax.swing.JRadioButton rbFlashing1;
    private javax.swing.JRadioButton rbGerakan0;
    private javax.swing.JRadioButton rbGerakan1;
    private javax.swing.JRadioButton rbGesekanBdn0;
    private javax.swing.JRadioButton rbGesekanBdn1;
    private javax.swing.JRadioButton rbInsang0;
    private javax.swing.JRadioButton rbInsang1;
    private javax.swing.JRadioButton rbLendir0;
    private javax.swing.JRadioButton rbLendir1;
    private javax.swing.JRadioButton rbLintah0;
    private javax.swing.JRadioButton rbLintah1;
    private javax.swing.JRadioButton rbNafsuMkn0;
    private javax.swing.JRadioButton rbNafsuMkn1;
    private javax.swing.JRadioButton rbPatogen0;
    private javax.swing.JRadioButton rbPatogen1;
    private javax.swing.JRadioButton rbPendarahanHidung0;
    private javax.swing.JRadioButton rbPendarahanHidung1;
    private javax.swing.JRadioButton rbPendarahanMata0;
    private javax.swing.JRadioButton rbPendarahanMata1;
    private javax.swing.JRadioButton rbPendarahanMulut0;
    private javax.swing.JRadioButton rbPendarahanMulut1;
    private javax.swing.JRadioButton rbPendarahanTutupInsang0;
    private javax.swing.JRadioButton rbPendarahanTutupInsang1;
    private javax.swing.JRadioButton rbPertumbuhan0;
    private javax.swing.JRadioButton rbPertumbuhan1;
    private javax.swing.JRadioButton rbSirip0;
    private javax.swing.JRadioButton rbSirip1;
    private javax.swing.JRadioButton rbSisik0;
    private javax.swing.JRadioButton rbSisik1;
    // End of variables declaration//GEN-END:variables
}
