/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakar.view;

import java.awt.event.ActionEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import sistempakar.controller.ControllerDiagnosa;

/**
 *
 * @author adesuryansyah
 */
public class ViewDiagnosa extends javax.swing.JInternalFrame {

   
 
    private boolean visible = false;
    ControllerDiagnosa  cbt;
  
    private int mata;
  
    /**
     * Creates new form diagnosa
     */
    public ViewDiagnosa() {
        initComponents();
        this.visible = false;
         
        
        cbt = new ControllerDiagnosa(this);
        
       
    }
    

    
    public boolean getVisible(){
        return visible;
    }
    
    public void setStatusVisible(boolean visible){
        this.visible = visible;
    }
    
    public ViewDiagnosa(int StartMata){
        mata = StartMata;
        int i = cbMata.getSelectedIndex();
        mata = i;
        
        return;
//        JOptionPane.showMessageDialog(rootPane, i);
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        bgPertumbuhan = new javax.swing.ButtonGroup();
        bgGerakan = new javax.swing.ButtonGroup();
        bgNafsuMakan = new javax.swing.ButtonGroup();
        bgGesekanBadan = new javax.swing.ButtonGroup();
        bgFalshing = new javax.swing.ButtonGroup();
        bgBorok = new javax.swing.ButtonGroup();
        bgPendarahanMata = new javax.swing.ButtonGroup();
        bgPendarahanMulut = new javax.swing.ButtonGroup();
        bgHidung = new javax.swing.ButtonGroup();
        bgTutupInsang = new javax.swing.ButtonGroup();
        bgInsang = new javax.swing.ButtonGroup();
        bgSisik = new javax.swing.ButtonGroup();
        bgLendir = new javax.swing.ButtonGroup();
        bgSirip = new javax.swing.ButtonGroup();
        bgPatogen = new javax.swing.ButtonGroup();
        bgLintah = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtIDPemeriksaan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUsia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbPertumbuhan0 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbGerakan1 = new javax.swing.JRadioButton();
        rbGerakan0 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbNafsuMkn1 = new javax.swing.JRadioButton();
        rbNafsuMkn0 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbGesekanBdn1 = new javax.swing.JRadioButton();
        rbGesekanBdn0 = new javax.swing.JRadioButton();
        rbFlashing0 = new javax.swing.JRadioButton();
        rbBorok0 = new javax.swing.JRadioButton();
        rbBorok1 = new javax.swing.JRadioButton();
        rbFlashing1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbPendarahanMata1 = new javax.swing.JRadioButton();
        rbPendarahanMata0 = new javax.swing.JRadioButton();
        rbPendarahanMulut0 = new javax.swing.JRadioButton();
        rbPendarahanMulut1 = new javax.swing.JRadioButton();
        rbPendarahanTutupInsang0 = new javax.swing.JRadioButton();
        rbPendarahanTutupInsang1 = new javax.swing.JRadioButton();
        rbPendarahanHidung1 = new javax.swing.JRadioButton();
        rbPendarahanHidung0 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbInsang1 = new javax.swing.JRadioButton();
        rbInsang0 = new javax.swing.JRadioButton();
        rbSisik0 = new javax.swing.JRadioButton();
        rbSisik1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbMata = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        rbLendir1 = new javax.swing.JRadioButton();
        rbLendir0 = new javax.swing.JRadioButton();
        rbSirip1 = new javax.swing.JRadioButton();
        rbSirip0 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rbPatogen1 = new javax.swing.JRadioButton();
        rbPatogen0 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        cbTubuh = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cbMati = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rbLintah0 = new javax.swing.JRadioButton();
        rbLintah1 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        cbEkor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnDiagnosa = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        rbPertumbuhan1 = new javax.swing.JRadioButton();

        jRadioButton25.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jRadioButton25.setText("RONTOK");

        jRadioButton26.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jRadioButton26.setText("MULUS");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel18.setText("10 . MATA");

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel23.setText("14. MATI");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setMaximizable(true);
        setTitle("Data Diagnosa");
        setFrameIcon(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID PEMERIKSAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(txtIDPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("USIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 20));
        getContentPane().add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 110, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("1. PERTUMBUHAN");

        rbPertumbuhan0.setBackground(new java.awt.Color(255, 255, 255));
        bgPertumbuhan.add(rbPertumbuhan0);
        rbPertumbuhan0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPertumbuhan0.setText("LAMBAT");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("2. GERAKAN");

        rbGerakan1.setBackground(new java.awt.Color(255, 255, 255));
        bgGerakan.add(rbGerakan1);
        rbGerakan1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGerakan1.setText("AKTIF");

        rbGerakan0.setBackground(new java.awt.Color(255, 255, 255));
        bgGerakan.add(rbGerakan0);
        rbGerakan0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGerakan0.setText("LAMBAT / LEMAH");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("3. NAFSU MAKAN");

        rbNafsuMkn1.setBackground(new java.awt.Color(255, 255, 255));
        bgNafsuMakan.add(rbNafsuMkn1);
        rbNafsuMkn1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbNafsuMkn1.setText("IYA");

        rbNafsuMkn0.setBackground(new java.awt.Color(255, 255, 255));
        bgNafsuMakan.add(rbNafsuMkn0);
        rbNafsuMkn0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbNafsuMkn0.setText("TIDAK");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel7.setText("6. BOROK");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel8.setText("5. FLASHING / BERENANG ");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel9.setText("4. GESEKAN BADAN");

        rbGesekanBdn1.setBackground(new java.awt.Color(255, 255, 255));
        bgGesekanBadan.add(rbGesekanBdn1);
        rbGesekanBdn1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGesekanBdn1.setText("IYA");

        rbGesekanBdn0.setBackground(new java.awt.Color(255, 255, 255));
        bgGesekanBadan.add(rbGesekanBdn0);
        rbGesekanBdn0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbGesekanBdn0.setText("TIDAK");

        rbFlashing0.setBackground(new java.awt.Color(255, 255, 255));
        bgFalshing.add(rbFlashing0);
        rbFlashing0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbFlashing0.setText("LAMBAT / LEMAH");

        rbBorok0.setBackground(new java.awt.Color(255, 255, 255));
        bgBorok.add(rbBorok0);
        rbBorok0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbBorok0.setText("TIDAK");

        rbBorok1.setBackground(new java.awt.Color(255, 255, 255));
        bgBorok.add(rbBorok1);
        rbBorok1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbBorok1.setText("IYA");

        rbFlashing1.setBackground(new java.awt.Color(255, 255, 255));
        bgFalshing.add(rbFlashing1);
        rbFlashing1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbFlashing1.setText("AKTIF");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel10.setText("     TIDAK BERATURAN");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setText("7. PENDARAHAN PADA :");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel12.setText("     - MATA");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel13.setText("     - MULUT");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel14.setText("     - HIDUNG");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel15.setText("     - TUTUP INSANG");

        rbPendarahanMata1.setBackground(new java.awt.Color(255, 255, 255));
        bgPendarahanMata.add(rbPendarahanMata1);
        rbPendarahanMata1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMata1.setText("IYA");

        rbPendarahanMata0.setBackground(new java.awt.Color(255, 255, 255));
        bgPendarahanMata.add(rbPendarahanMata0);
        rbPendarahanMata0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMata0.setText("TIDAK");

        rbPendarahanMulut0.setBackground(new java.awt.Color(255, 255, 255));
        bgPendarahanMulut.add(rbPendarahanMulut0);
        rbPendarahanMulut0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMulut0.setText("TIDAK");

        rbPendarahanMulut1.setBackground(new java.awt.Color(255, 255, 255));
        bgPendarahanMulut.add(rbPendarahanMulut1);
        rbPendarahanMulut1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanMulut1.setText("IYA");

        rbPendarahanTutupInsang0.setBackground(new java.awt.Color(255, 255, 255));
        bgTutupInsang.add(rbPendarahanTutupInsang0);
        rbPendarahanTutupInsang0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanTutupInsang0.setText("TIDAK");

        rbPendarahanTutupInsang1.setBackground(new java.awt.Color(255, 255, 255));
        bgTutupInsang.add(rbPendarahanTutupInsang1);
        rbPendarahanTutupInsang1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanTutupInsang1.setText("IYA");

        rbPendarahanHidung1.setBackground(new java.awt.Color(255, 255, 255));
        bgHidung.add(rbPendarahanHidung1);
        rbPendarahanHidung1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanHidung1.setText("IYA");

        rbPendarahanHidung0.setBackground(new java.awt.Color(255, 255, 255));
        bgHidung.add(rbPendarahanHidung0);
        rbPendarahanHidung0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPendarahanHidung0.setText("TIDAK");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("8. INSANG");

        rbInsang1.setBackground(new java.awt.Color(255, 255, 255));
        bgInsang.add(rbInsang1);
        rbInsang1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbInsang1.setText("MERAH HATI");

        rbInsang0.setBackground(new java.awt.Color(255, 255, 255));
        bgInsang.add(rbInsang0);
        rbInsang0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbInsang0.setText("PUCAT");

        rbSisik0.setBackground(new java.awt.Color(255, 255, 255));
        bgSisik.add(rbSisik0);
        rbSisik0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSisik0.setText("RONTOK");

        rbSisik1.setBackground(new java.awt.Color(255, 255, 255));
        bgSisik.add(rbSisik1);
        rbSisik1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSisik1.setText("MULUS");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel16.setText("9. SISIK");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel17.setText("10 . MATA");

        cbMata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bersih", "Rontok", "Kemerahan", "Rontok dan Kemerahan" }));
        cbMata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMataActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel19.setText("11. LENDIR");

        rbLendir1.setBackground(new java.awt.Color(255, 255, 255));
        bgLendir.add(rbLendir1);
        rbLendir1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLendir1.setText("NORMAL");

        rbLendir0.setBackground(new java.awt.Color(255, 255, 255));
        bgLendir.add(rbLendir0);
        rbLendir0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLendir0.setText("BERLEBIHAN");

        rbSirip1.setBackground(new java.awt.Color(255, 255, 255));
        bgSirip.add(rbSirip1);
        rbSirip1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSirip1.setText("MULUS");

        rbSirip0.setBackground(new java.awt.Color(255, 255, 255));
        bgSirip.add(rbSirip0);
        rbSirip0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbSirip0.setText("RUSAK");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel20.setText("12. SIRIP");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel21.setText("13. PATOGEN");

        rbPatogen1.setBackground(new java.awt.Color(255, 255, 255));
        bgPatogen.add(rbPatogen1);
        rbPatogen1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPatogen1.setText("NORMAL");

        rbPatogen0.setBackground(new java.awt.Color(255, 255, 255));
        bgPatogen.add(rbPatogen0);
        rbPatogen0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPatogen0.setText("RENDAH");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel22.setText("14. MATI");

        cbTubuh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bersih", "Menghitam", "Putih atau bercorak keputihan" }));
        cbTubuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTubuhActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel24.setText("15. TUBUH");

        cbMati.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak", "<5 ekor", ">= ekor" }));

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel25.setText("16. APAKAH TERDAPAT  LINTAH ATAU WARNA KEHITAMAN");

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel26.setText("        PADA SIRIP DAN TUTUP INSANG");

        rbLintah0.setBackground(new java.awt.Color(255, 255, 255));
        bgLintah.add(rbLintah0);
        rbLintah0.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLintah0.setText("TIDAK");

        rbLintah1.setBackground(new java.awt.Color(255, 255, 255));
        bgLintah.add(rbLintah1);
        rbLintah1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbLintah1.setText("IYA");

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel28.setText("17. EKOR");

        cbEkor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bersih", "Rontok", "Kemerahan", "Rontok dan Kemrahan" }));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        btnDiagnosa.setBackground(new java.awt.Color(204, 0, 0));
        btnDiagnosa.setForeground(new java.awt.Color(255, 255, 255));
        btnDiagnosa.setText("DIAGNOSA");
        btnDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosaActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 255, 51));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REFRESH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiagnosa)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(jButton2)
                    .addComponent(btnDiagnosa))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("IKAN INI TERDIAGNOSA PENYAKIT :");

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("PENCEGAHAN :");

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("PENANGGULANGAN :");

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("SARAN :");

        jButton4.setBackground(new java.awt.Color(255, 102, 51));
        jButton4.setText("LIHAT SEMUA DATA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(34, 34, 34))))
        );

        rbPertumbuhan1.setBackground(new java.awt.Color(255, 255, 255));
        bgPertumbuhan.add(rbPertumbuhan1);
        rbPertumbuhan1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        rbPertumbuhan1.setText("Normal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbBorok1)
                    .addComponent(rbGerakan1)
                    .addComponent(rbNafsuMkn1)
                    .addComponent(rbGesekanBdn1)
                    .addComponent(rbFlashing1)
                    .addComponent(rbPertumbuhan1)
                    .addComponent(rbPendarahanHidung1)
                    .addComponent(rbPendarahanMulut1)
                    .addComponent(rbPendarahanTutupInsang1)
                    .addComponent(rbPendarahanMata1)
                    .addComponent(rbInsang1)
                    .addComponent(rbSisik1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFlashing0)
                    .addComponent(rbBorok0)
                    .addComponent(rbGesekanBdn0)
                    .addComponent(rbNafsuMkn0)
                    .addComponent(rbGerakan0)
                    .addComponent(rbPertumbuhan0)
                    .addComponent(rbPendarahanMulut0)
                    .addComponent(rbPendarahanMata0)
                    .addComponent(rbPendarahanHidung0)
                    .addComponent(rbPendarahanTutupInsang0)
                    .addComponent(rbSisik0)
                    .addComponent(rbInsang0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(29, 29, 29)
                            .addComponent(rbLendir1)
                            .addGap(18, 18, 18)
                            .addComponent(rbLendir0))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(rbSirip1)
                            .addGap(24, 24, 24)
                            .addComponent(rbSirip0))
                        .addComponent(jLabel20)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbLintah1)
                                    .addGap(47, 47, 47)))
                            .addComponent(rbLintah0))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(34, 34, 34)
                            .addComponent(cbMata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbPatogen1)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbPatogen0))
                                .addComponent(cbTubuh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMati, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEkor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbMata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbLendir1)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbLendir0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(rbSirip1)
                            .addComponent(rbSirip0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(rbPatogen1)
                            .addComponent(rbPatogen0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(cbMati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTubuh)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbLintah0)
                                    .addComponent(rbLintah1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEkor)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbPertumbuhan0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbGerakan0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbNafsuMkn0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbGesekanBdn0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(rbBorok0))
                                    .addComponent(rbFlashing0))
                                .addGap(18, 18, 18)
                                .addComponent(rbPendarahanMata0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPendarahanMulut0)
                                .addGap(0, 0, 0)
                                .addComponent(rbPendarahanHidung0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPendarahanTutupInsang0)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbInsang0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(rbSisik0))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbPertumbuhan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbGerakan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNafsuMkn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbGesekanBdn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(rbBorok1))
                            .addComponent(rbFlashing1))
                        .addGap(18, 18, 18)
                        .addComponent(rbPendarahanMata1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPendarahanMulut1)
                        .addGap(0, 0, 0)
                        .addComponent(rbPendarahanHidung1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPendarahanTutupInsang1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInsang1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSisik1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        setStatusVisible(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        setStatusVisible(true);
    }//GEN-LAST:event_formInternalFrameIconified

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       
        rbPertumbuhan0.setActionCommand("0");
        rbPertumbuhan1.setActionCommand("1");
        
        rbGerakan0.setActionCommand("0");
        rbGerakan1.setActionCommand("1");
        
        rbNafsuMkn0.setActionCommand("0");
        rbNafsuMkn1.setActionCommand("1");
        
        rbGesekanBdn0.setActionCommand("0");
        rbGesekanBdn1.setActionCommand("1");
        
        rbFlashing0.setActionCommand("0");
        rbFlashing1.setActionCommand("1");
        
        rbPendarahanMata0.setActionCommand("0");
        rbPendarahanMata1.setActionCommand("1");
        
        rbPendarahanMulut0.setActionCommand("0");
        rbPendarahanMulut1.setActionCommand("1");
        
        rbPendarahanHidung0.setActionCommand("0");
        rbPendarahanHidung1.setActionCommand("1");
        
        rbPendarahanTutupInsang0.setActionCommand("0");
        rbPendarahanTutupInsang1.setActionCommand("1");
        
        rbBorok0.setActionCommand("0");
        rbBorok1.setActionCommand("1");
        
        rbInsang0.setActionCommand("0");
        rbInsang1.setActionCommand("1");
        
        rbSisik0.setActionCommand("0");
        rbSisik1.setActionCommand("1");
        
        rbLendir0.setActionCommand("0");
        rbLendir1.setActionCommand("1");
        
        rbSirip0.setActionCommand("0");
        rbSirip1.setActionCommand("1");
        
        rbPatogen0.setActionCommand("0");
        rbPatogen1.setActionCommand("1");
        
        rbLintah0.setActionCommand("0");
        rbLintah1.setActionCommand("1");
        
        
         
        cbt.insert();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void cbMataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMataActionPerformed
        

        
    }//GEN-LAST:event_cbMataActionPerformed

    private void cbTubuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTubuhActionPerformed
       
    }//GEN-LAST:event_cbTubuhActionPerformed

    private void btnDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosaActionPerformed
        popUpDiagnosa p = new popUpDiagnosa();
        this.getParent().add(p);
        p.setVisible(true);
        
    }//GEN-LAST:event_btnDiagnosaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgBorok;
    private javax.swing.ButtonGroup bgFalshing;
    private javax.swing.ButtonGroup bgGerakan;
    private javax.swing.ButtonGroup bgGesekanBadan;
    private javax.swing.ButtonGroup bgHidung;
    private javax.swing.ButtonGroup bgInsang;
    private javax.swing.ButtonGroup bgLendir;
    private javax.swing.ButtonGroup bgLintah;
    private javax.swing.ButtonGroup bgNafsuMakan;
    private javax.swing.ButtonGroup bgPatogen;
    private javax.swing.ButtonGroup bgPendarahanMata;
    private javax.swing.ButtonGroup bgPendarahanMulut;
    private javax.swing.ButtonGroup bgPertumbuhan;
    private javax.swing.ButtonGroup bgSirip;
    private javax.swing.ButtonGroup bgSisik;
    private javax.swing.ButtonGroup bgTutupInsang;
    private javax.swing.JButton btnDiagnosa;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbEkor;
    private javax.swing.JComboBox<String> cbMata;
    private javax.swing.JComboBox<String> cbMati;
    private javax.swing.JComboBox<String> cbTubuh;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton rbBorok0;
    private javax.swing.JRadioButton rbBorok1;
    private javax.swing.JRadioButton rbFlashing0;
    private javax.swing.JRadioButton rbFlashing1;
    private javax.swing.JRadioButton rbGerakan0;
    private javax.swing.JRadioButton rbGerakan1;
    private javax.swing.JRadioButton rbGesekanBdn0;
    private javax.swing.JRadioButton rbGesekanBdn1;
    private javax.swing.JRadioButton rbInsang0;
    private javax.swing.JRadioButton rbInsang1;
    private javax.swing.JRadioButton rbLendir0;
    private javax.swing.JRadioButton rbLendir1;
    private javax.swing.JRadioButton rbLintah0;
    private javax.swing.JRadioButton rbLintah1;
    private javax.swing.JRadioButton rbNafsuMkn0;
    private javax.swing.JRadioButton rbNafsuMkn1;
    private javax.swing.JRadioButton rbPatogen0;
    private javax.swing.JRadioButton rbPatogen1;
    private javax.swing.JRadioButton rbPendarahanHidung0;
    private javax.swing.JRadioButton rbPendarahanHidung1;
    private javax.swing.JRadioButton rbPendarahanMata0;
    private javax.swing.JRadioButton rbPendarahanMata1;
    private javax.swing.JRadioButton rbPendarahanMulut0;
    private javax.swing.JRadioButton rbPendarahanMulut1;
    private javax.swing.JRadioButton rbPendarahanTutupInsang0;
    private javax.swing.JRadioButton rbPendarahanTutupInsang1;
    private javax.swing.JRadioButton rbPertumbuhan0;
    private javax.swing.JRadioButton rbPertumbuhan1;
    private javax.swing.JRadioButton rbSirip0;
    private javax.swing.JRadioButton rbSirip1;
    private javax.swing.JRadioButton rbSisik0;
    private javax.swing.JRadioButton rbSisik1;
    private javax.swing.JTextField txtIDPemeriksaan;
    private javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables


    
    public JTextField getIDPemeriksaan(){
        return txtIDPemeriksaan;
    }
    
    public JTextField getUsia(){
        return txtUsia;
    }  
    
    public ButtonGroup getbgPertumbuhan(){
        return bgPertumbuhan;
    }
    
   public ButtonGroup getbgGerakan(){
       return bgGerakan;
   }
   
   public ButtonGroup getbgNafsuMakan(){
       return bgNafsuMakan;
   }
   
   public ButtonGroup getbgGesekanBadanJaring(){
       return bgGesekanBadan;
   }
   
   public ButtonGroup getbgFlashing(){
       return bgFalshing;
   }
   
   public ButtonGroup getbgPendrahanMata(){
       return bgPendarahanMata;
   }
   
   public ButtonGroup getbgPendarahanMulut(){
       return bgPendarahanMulut;
   }
   
   public ButtonGroup getbgPendarahanHidung(){
       return bgHidung;
   }
   
   public ButtonGroup getbgTutupInsang(){
       return bgTutupInsang;
   }
   
   public ButtonGroup getBgBorok(){
       return bgBorok;
   }
   
   public ButtonGroup getBgInsang(){
       return bgInsang;
   }
   
   public ButtonGroup getBgSirip(){
       return bgSirip;
   }
   
   public ButtonGroup getBgSisik(){
       return bgSisik;
   }
   
   public ButtonGroup getBgLendir(){
       return bgLendir;
   }
   
   public ButtonGroup getBgPatogen(){
       return bgPatogen;
   }
   
   public ButtonGroup getBgLintah(){
       return bgLintah;
   }
   
   public String getCbMata(){

          String VMata = null;
          Object selected = cbMata.getSelectedItem();
          if(selected.toString().equals("Bersih")){
            VMata = "0";
          }if(selected.toString().equals("Rontok")){
            VMata = "0.25";
          }
          if(selected.toString().equals("Kemerahan")){
            VMata = "0.5";
          }
          if(selected.toString().equals("ROntok dan Kemerahan")){
            VMata = "1";
          }

    return VMata;
   }
   
   public String getCbMati(){
       String VMati = null;
       Object selected = cbMati.getSelectedItem();
       if(selected.toString().equals("Tidak")){
            VMati = "0";
          }
          if(selected.toString().equals("<5 ekor")){
            VMati = "0.5";
          }
          if(selected.toString().equals(">= ekor")){
            VMati = "1";
          }
          return VMati;
   }
   
   public String getCbTubuh(){
       String VTubuh = null;
       Object selected = cbTubuh.getSelectedItem();
       if(selected.toString().equals("Bersih")){
            VTubuh = "0";
          }
          if(selected.toString().equals("Menghitam")){
            VTubuh = "0.5";
          }
          if(selected.toString().equals("Putih atau bercorak keputihan")){
            VTubuh = "1";
          }
          return VTubuh;
   }

   public String getCbEkor(){
       String VEkor = null;
       Object selected = cbEkor.getSelectedItem();
       if(selected.toString().equals("Bersih")){
            VEkor = "0";
          }
          if(selected.toString().equals("Rontok")){
            VEkor = "0.25";
          }
          if(selected.toString().equals("Kemerahan")){
            VEkor = "0.5";
          }
          if(selected.toString().equals("Rontok dan kemerahan")){
            VEkor = "1";
          }
          return VEkor;
   }
   
   
   
}


